### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by dometto** [grackorg/grack#2]
@jackbean818 reports problems on windows:

> was giving me "invalid length sets" or "bad length character" errors when running grack on Windows.
> Turns out that the pipe under service_rpc() needs to be opened with binary mode, otherwise Windows writes \r\n instead of just \n.
> It works if I change it to IO.popen(command, "r+b")

If I change the mode [here](https://github.com/grackorg/grack/blob/master/lib/git_adapter.rb#L19) to `"w+b"` I get `ERROR IOError: closed stream` on unix/OS X. Unfortunately, I don't have access to Windwos. So the question is:
1. Is this still an issue on Windows with the latest grack (and all the updates to git from the past years)?
2. If so, does changing the mode to `"w+b" solve the problem, and do the tests still pass then?

In that case, the fix is to set the filemode conditional on the operating system.

**Comment by javanthropus** [comment]
You should be able to use `"r+b"` rather than `"w+b"`.  I've made a fix for this on my repository's master branch, and all my tests continue to pass on Linux.  I should be able to verify this on a Windows system within the next few days, but this is a pretty common solution.

**Comment by javanthropus** [comment]
I just rediscovered this issue and finally set up a test rig in Windows.  Unfortunately, newer versions of git break `GitAdapterTest#test_receive_pack` due to the addition of some new items in the list of metadata git provides.  It breaks on Linux in the same way, so this to requires the test be updated a bit to account for the new output.   Fortunately, that change is simple, and it proves that this issue itself is already fixed.

I have pushed the updated test to the `update_expected_git_output branch` of this repository.
